name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: pass
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          push: true
          tags: fatimaghafoor/api-gateway:latest

      - name: Build and push Customer Service
        uses: docker/build-push-action@v2
        with:
          context: ./customer-services
          push: true
          tags: fatimaghafoor/customer-services:latest

      - name: Build and push Inventory Service
        uses: docker/build-push-action@v2
        with:
          context: ./inventory-services
          push: true
          tags: fatimaghafoor/inventory-services:latest

      - name: Build and push Menu Service
        uses: docker/build-push-action@v2
        with:
          context: ./menu-services
          push: true
          tags: fatimaghafoor/menu-services:latest

      - name: Build and push Order Service
        uses: docker/build-push-action@v2
        with:
          context: ./order-services
          push: true
          tags: fatimaghafoor/order-services:latest

      - name: Build and push Payment Service
        uses: docker/build-push-action@v2
        with:
          context: ./payment-services
          push: true
          tags: fatimaghafoor/payment-services:latest

      - name: Deploy to Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml logs -f